# Generated by Django 2.2.17 on 2021-12-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('distance', models.PositiveIntegerField(default=1, verbose_name='Расстояние')),
            ],
        ),
    ]
