# Generated by Django 2.2.17 on 2021-12-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spa',
            name='created_at',
            field=models.DateField(blank=True, editable=False, verbose_name='Дата'),
        ),
    ]
