# Generated by Django 2.2.17 on 2021-12-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20211214_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spa',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
